n1 = input ("Please enter the input")
n = int(n1)
i = 0
j = n - 1
k = 1
g = 0
d = 0
a = 0
q = 0
while (i <=n):
    while (k <= j):
        print ("  ",end="")
        k = k+1
    print ("*",end="")
    j = j-1
    k =0
    while (a <= q):
        print ("*",end="")
        a = a+1
    a = 0
    q = q+1