distance = input ("Please enter distance in km= ")
time = input ("Please enter the time in hours= ")
distance1= int(distance)
time1= int(time)
speed = (distance1/time1)
print ("Speed=",speed,"kph")