a = input ("Name \n")
n = input ("Nationality\n ")
i =input ("Gender \n")
r =input ("Religion \n")
print ("\n")
print ("Name : "+a)
print ("Nationality:"+n)
print ("Gender : "+i)
print ("Religion : "+r)